### ISSUE TITLE
How disable log in mongo conteiner?

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [docker-library/mongo#103]
In mongo version 2.6 have issue with filling disk 1Gb/day. After restart container space is cleaning and again filling disk. I thing need disable log (or redirect to /dev/null for showing in `docker logs mongo` )

**Comment by Evgeniy-Bondarenko** [comment]
may be mongo-docker have attributes for change path log?

**Comment by yosifkit** [comment]
I have a mongo container that was created 6 months ago and I don't see any log files within the container taking space.  I even checked in my mounted volume and it only has the database files.  I do see my logs in `docker logs`.

```console
$ docker diff mongo
C /tmp
A /tmp/mongodb-27017.sock
C /root
A /root/.dbshell
A /root/.mongorc.js
```

By default mongod logs to stdout, so running `docker run -d --name some-mongo mongo:2.7` will make all logs available in `docker logs some-mongo`.  If you need to set limits on those logs, check out [configuring log drivers](https://docs.docker.com/engine/admin/logging/overview/#/json-file-options). You could also configure it to point to gelf, syslog, or another logging service.

If you just want to change where mongod logs, then you can pass the `--logpath` option to it: `docker run -d --name some-mongo mongo:2.7 --logpath /var/log/mongodb/server1.log --logappend`.  You'll probably need to ensure the folder exists with the correct permissions in the container. With this route you would probably want to look in to having `mongod` open a new file on some sort of schedule https://docs.mongodb.com/v2.6/tutorial/rotate-log-files/, so that you can delete older logs.

**Comment by yosifkit** [comment]
Closing old issue. Feel free to comment on further troubleshooting if you feel this was closed in error or on the solution to help users running into the same problem.
