### ISSUE TITLE
Dockerhub documentation

### ISSUE THREAD

**Issue by RobertDiebels** [docker-library/mongo#134]
Hi guys,

This is not really a bug. More of an update/state request.

I was wondering if you've update the dockerhub [documentation ](https://hub.docker.com/_/mongo/ ) lately.

I'm fiddling around with docker and mongo and I'm using networks intead of `--link` which is [deprecated](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/). However your documentation still references `--link`.

I was wondering if you can provide a more up-to-date version of the documentation and validate that using networks also works.

**Comment by yosifkit** [comment]
We use `--link` since it still has not been deprecated in the cli, just the documentation (there is still no warning when using it).  It really is the simplest way to test a multi-container setup and doesn't require you to remember to clean up the network that you created.

One major change to use a network instead of a link is not using the special environment variables.  The second is that you need a network alias if the name of the other container is not the same as the dns name used to access it.
```console
$ docker network create mongo
$ docker run --name some-mongo -d --network mongo --network-alias mongo mongo
$ docker run -it --rm --network mongo mongo mongo mongo/mongo
$ # [network mongo] [image mongo] [command mongo] [host/database mongo]
```

**Comment by RobertDiebels** [comment]
@yosifkit Ah great thank you! I thought it was already deprecated. I never used `--link` as a result. 
I've been using `--network` for a while now so I'm familiar with it's usage. 

I was just wondering if there could have been anything that blocked the mongo image/container from being able to use it. Or if it might be the case you didn't update the docs yet. Which doesn't appear to be the case. Which is good news for me :D !

Thanks again!
