### ISSUE TITLE
Database initialisation scripts and custom db path

### ISSUE THREAD

**Issue by deployable** [docker-library/mongo#148]
I use `FROM mongo` in Dockerfiles that occasionally setup custom mongo db paths.

It would be useful to have the initialisation scripts work in these circumstances, currently initialisation scripts run repeatedly as `/data/db` is never initialised. 

Detecting `--dbpath` on the command line isn't too hard. Detecting `dbPath` in a config file is a bit harder. 

Another option could be using a "state" file, possibly one for each of the "user" and "init" steps, stored in the container somewhere on successful init. Was that approach considered/avoided for the current implementation?

**Comment by deployable** [comment]
I think most of these were to do database initialisation and avoid the `/data/db` `VOLUME` definition. Some could probably just move to using the new init setup.

**Comment by yosifkit** [comment]
Sorry to break your Dockerfiles. :disappointed: 

We didn't detect dbpath since that would require finding and parsing all config files along with the command line arguments. (We can cheat with postgres since it uses the `PGDATA` variable automatically).

We considered a state file somewhere in the image, but it doesn't help when deleting the container and starting a new version with the same database files.

I would say :+1: to using the new init rather than storing the db in the image.  The union file system in use (aufs, overlay, etc) for image layers can have negative impact on high I/O.

**Comment by deployable** [comment]
No worries, only testing using the new features. 

Thanks for the details. It probably just needs a documentation line to say init doesn't support paths other than `/data/db`.

**Comment by sdanieru** [comment]
Hi tianon, thanks for the swift response! I'm not sure I completely understand the problem, but will changing the container's internal db path to the default (i.e. /data/db) solve the problem?
