### ISSUE TITLE
Environment variable set up by linking mongo container counterintuitive

### ISSUE THREAD

**Issue by MattMoranJava** [docker-library/mongo#178]
I found this trying to run a named mongodb container (called mongodb) linked to a tomcat 8 & jre8 container. In my Spring webapp, there's a db.properties file which lays out a number of properties for the database:
`mongodb.host=mongodb
mongodb.port=27017
mongodb.database=mydatabase`
etc. This supplies values to a MongoConfig class, which uses Spring to specify that the values should come from this file, and also to set various fields to the values given in the properties file.
So far, so good. However, when I fire up the webapp in the Tomcat container, with the mongo container linked as 
`--link mongodb:mongodb`
it falls over. Somehow mongodb.port is being set to a String, "tcp://172.17.0.2:27017" & that's causing a problem. 

Some investigation shows me that within the Tomcat container, by virtue of the --link, there's an environment variable MONGODB_PORT which is set to this string value. Spring is somehow picking up on this & overriding the properties file value. 

"Why am I raising this here?", you're probably asking. Well, I have a workaround of course, which is to name my mongodb container differently, BUT the fact remains, there's an *address* in an environment variable labelled X_*PORT*. I'd like to suggest that if the variable needs to contain an address, then it should be called X_*ADDRESS* instead. This would save headaches, I think.

Is this something that can be changed at this level, or would it be something I need to contact the people who make mongo directly about?

**Comment by yosifkit** [comment]
That is part of the automatic variables that come from docker linking. Best documentation I've found is in the compose docs: https://docs.docker.com/compose/link-env-deprecated/.  The solution is to instead create a docker network (`docker network create db-net`) and then run each container in that network instead of using `--link`, `docker run --network db-net ...`.  They'll be able to resolve other containers within the network by their container name using docker's built-in DNS automatically.

**Comment by kamal-github** [comment]
@yosifkit Thanks a lot for the link, I have searched this and having so much trouble in finding connecting mongo service to go service. You saved me! :)
