### ISSUE TITLE
Mongo user in dockerfile added as default system user uid.

### ISSUE THREAD

**Issue by jamesongithub** [docker-library/mongo#181]
The dockerfile adds mongodb user as system user which in turn creates a user with a uid of 999.

![image](https://cloud.githubusercontent.com/assets/4452738/26265355/b128a778-3c95-11e7-82da-8cbc9e5a8145.png)

On our host we happen to have another default system user with a uid of 999.

![image](https://cloud.githubusercontent.com/assets/4452738/26265389/cf6cc9bc-3c95-11e7-9e39-ed9db2e7b586.png)

When we run the docker container it gets mapped to this user.

![image](https://cloud.githubusercontent.com/assets/4452738/26265404/dafeacfa-3c95-11e7-8915-9936b74c6804.png)

I'm wondering what people have done to get around this. Basically the container has all the rights of the mapped user now.

**Comment by yosifkit** [comment]
While the mongo user is user 999, it can only access things given to it inside the container.

https://github.com/docker-library/mongo/pull/81 added the ability to run as an arbitrary user, `docker run --user some-other-user-id:some-group-id` (up to you to ensure chosen user/group has access to any bind mounted files).

**Comment by jamesongithub** [comment]
in this case. user 999 can access the container tho right.

i guess we'll go with a random uid then. thanks.

**Comment by jamesongithub** [comment]
@yosifkit getting this running as another user

```
17:51:29 2017-05-22T17:51:28.895+0000 I CONTROL  [initandlisten] options: {}
17:51:29 2017-05-22T17:51:28.912+0000 I STORAGE  [initandlisten] exception in initAndListen: 98 Unable to create/open lock file: /data/db/mongod.lock errno:13 Permission denied Is a mongod instance already running?, terminating
```

i'm not using a host volume

does the startup handle chowning the data directory to the user passed it?

**Comment by yosifkit** [comment]
It cannot chown. If you start the container with `--user` to docker run, then it is not root and cannot chown files owned by another user. It seems that #81 did not chmod 777 the directory in the Dockerfile since that would be insecure for database files. So I think if you want to run as a specific user, you have to provide a data directory that it can write to.

We did add some notes for arbitrary users in [postgres](https://github.com/docker-library/docs/tree/f2c929c3a54bee39f08d65686c691606ca87707b/postgres#arbitrary---user-notes), but have not added anything for mongo, mysql, mariadb, or percona.

**Comment by jamesongithub** [comment]
in that case, think id prefer to run it as the user starting the container, however in that case that user needs to exist in the container then

**Comment by mangalbhaskar** [comment]
Old thread, but posting the solution in case someone finds it useful. Currently, it has different options to get this working, but you need to justify your case. For example, in my case, the data volume is mapped to the mongodb docker container created using official mongodb docker image, it always creates the mongodb uid=999 and gid=999.

**Problem**
* In specific case of **Kali Linux (this is what I am using)**: uid, gid 999 maps to user: **systemd-coredump**
* **/etc/passwd entry:** `systemd-coredump:x:999:999:systemd Core Dumper:/:/sbin/nologin`
* It's may not be the real problem because only the specific user only can edit/modify the data, but not sure about the side effects of using the **systemd-coredump** user outside the container but which was mapped to **mongodb** user inside the container

**Solution**
a) create a mongodb user and group on the host machine
b) pass the user, group, uid, gid as arguments to the official mongodb dockerfile
b) build the image by passing the values to the respective arguments

[Details and scripts here](https://github.com/mangalbhaskar/mongo/tree/master/4.1)

**Comment by superstes** [comment]
If someone comes across this again:
You can see how to re-build the official docker-image, to use a custom UID/GID, with minimal changes here:
- https://github.com/superstes/docker-mongodb-uid

Greetings

**Comment by tianon** [comment]
If that's really necessary, wouldn't something like this be simpler?

```dockerfile
FROM mongo:6
RUN set -eux; \
	groupmod --gid 1234 mongodb; \
	usermod --uid 1234 mongodb
```

(At most, then adding `chown -R mongodb:mongodb /var/log/mongodb /data/configdb /data/db` afterwards :sweat_smile:)

**Comment by superstes** [comment]
Could be a simpler solution, yes. Will test it.
Thanks for the feedback.

**Comment by superstes** [comment]
Tested and added the option + examples to my repo.
Thanks
