### ISSUE TITLE
Add healthcheck to docker

### ISSUE THREAD

**Issue by elpadrinoIV** [docker-library/mongo#216]
Provide docker image with healthcheck validation.

For example:

`/healthcheck.sh`
```sh
#!/bin/bash

set -e

STATUS=`echo "db.stats().ok" | mongo --quiet`
if [ $? -ne 0 ]; then
    exit 1
fi

if [ "$STATUS" -eq 1 ]; then
    exit 0
else
    exit 1
fi
```

And then in the Dockerfile:
```Dockerfile
COPY healthcheck.sh /healthcheck.sh
HEALTHCHECK CMD /healthcheck.sh
```

**Comment by qedrakmar** [comment]
You can set health checks in a compose file, if the system is running is swarm mode.  Upload the file with COPY in your Dockerfile, then execute the healthchecks as defined [here](https://docs.docker.com/engine/reference/commandline/service_create/#options) (scroll down to the 5 options that start with "--health").

You can do health checks in Kubernetes with [readinessProbes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/).

This is otherwise unrelated to the Mongo image, so I am closing this issue.  

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
