### ISSUE TITLE
In Memory Support

### ISSUE THREAD

**Issue by XPLOT1ON** [docker-library/mongo#224]
Would love to see an option that turns MongoDB instance into an in-memory database (through MongoDB configuration, not docker tmpfs.

**Comment by tianon** [comment]
Given https://docs.mongodb.com/manual/core/inmemory/, it should be as
simple as passing "--storageEngine inMemory" to the container.

**Comment by XPLOT1ON** [comment]
@tianon  yes, that is true. However, I was looking for a feature support with this docker image. perhaps through the environment variable that will turn the database into an in-memory DB.

**Comment by tianon** [comment]
Correct, passing arbitrary flags to `mongod` is as close to "a feature of this image" as we get, in this case (since adjusting the command of the image is as trivial as adding environment variables).

However, I did need to read that link a little closer -- the `inMemory` storage engine is _only_ supported for MongoDB Enterprise (not community edition, which is what this image packages); see https://github.com/docker-library/mongo/pull/185 for more information about how one could build the enterprise edition from the sources of this community edition image.

**Comment by XPLOT1ON** [comment]
Right, thanks for pointing that out. I didn't notice that the feature is an enterprise only. Even before creating this post.

**Comment by MichaRedM** [comment]
You can use tmpfs to create an inMemory filesystem over docker.

In your docker compose you declare the following volume:
```yml
services:
    mongo:
        image: mongo:4.2
        volumes:
            - type: tmpfs
              target: /data/db
```

**Comment by IliasDeros** [comment]
Another option, without tmpfs, is to use [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server).

Just run the library as a node service. **Example:**
https://gist.github.com/IliasDeros/9d23f55173e6487ecb681caabf596923
