### ISSUE TITLE
Loss of data when using bind-mounts, is this expected behaviour?

### ISSUE THREAD

**Issue by jaywick** [docker-library/mongo#230]
I usually run the mongo container with the `-v` option (bind mount)

    docker run --name foo -v /data/db:/data/db -d mongo

But recently ran the container without it

    docker run --name foo -d mongo

But rerunning mongo with the -v option again to `/data/db` shows that the data is gone (db, collections, the lot).

Is this expected behaviour? And if so why is that happening? Would using `volumes` avoid this?

**Comment by tianon** [comment]
This is definitely not the expected behavior and sounds very bizarre (I've never seen anything like that).

When you do `-v /data/db:/data/db`, you're telling Docker that you want the `/data/db` folder from your host bind-mounted directly into the container at `/data/db`.  When you don't specify that, Docker will create a new volume (under `/var/lib/docker/volumes`) which gets mounted instead (and `/data/db` on your host remains untouched).

Anything else running on the machine which might have touched `/data/db` on the host?  Any other containers using that mount?  Does `/data/db` still exist on the host?  Are there files inside?

The only other thing I can think of is that perhaps you somehow managed to have your MongoDB instance exposed publicly, and thus were a victim of https://www.bleepingcomputer.com/news/security/massive-wave-of-mongodb-ransom-attacks-makes-26-000-new-victims/, but that doesn't seem possible if you're running via the exact command given here. :confused:

**Comment by jaywick** [comment]
I can't actually repro this issue any more, I'm going to chalk it down to user error. Apologies!
