### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by KevinBurton** [docker-library/mongo#233]
Should I use a volume for configuration? If so what would be the mount point? Is this mount point a file or folder?

**Comment by tianon** [comment]
I'd recommend using command line flags for configuration, personally (they're much easier to deal with in my experience).

If you _must_ use a config file, it will be a single file, can be stored wherever you want, and requires `-f /path/to/config/file.yml` to be passed on the container command line in order to tell `mongod` where the configuration file is stored.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
