### ISSUE TITLE
Can not keep the data in the external folder

### ISSUE THREAD

**Issue by demas** [docker-library/mongo#25]
I have been trying to run the container using:

`docker run --name mongo-db -d -p 27017:27017 -v  /mnt/lacie/databases/mongo/data:/data mongo`

or:

`docker run --name mongo-db -d -p 27017:27017 -v /mnt/lacie/databases/mongo/data/db:/data/db mongo`.

Next I connect to mongodb, create a db, a collection and insert data on it.

I can stop the container `docker stop`, run it again `docker start` and all the data changes will be present in the database.

If I remove container `docker rm` and create new one - the data dissapear. Why and how can I fix it?

**Comment by yosifkit** [comment]
I tried the two options you show and only the second works because the VOLUME declared in the Dockerfile will be mounted on top of `/data/db` on the first and the write would then never go to the bind mount.

```console
$ docker run -d --name mongo-db -v /docker/tmp/mongo/db:/data/db mongo
$ docker run -it --rm --link mongo-db:mongo mongo mongo mongo/mongo
# do some inserts in the mongo shell

$ docker stop mongo-db
$ docker rm mongo-db

$ docker run -d --name mongo-db -v /docker/tmp/mongo/db:/data/db mongo
$ docker run -it --rm --link mongo-db:mongo mongo mongo mongo/mongo
# see data that was previously inserted
```

Did you check the `/mnt/lacie/databases/mongo/data/db` directory for the db files?  Was the container able to write there?

**Comment by FreakTheMighty** [comment]
I have been running into the same issues as @demas. I've been testing `docker-compose`. When I configure the mongo instance like so nothing is written into the host file system. I am using Boot2Docker-cli version: v1.5.0

```
db:
  image: mongo
  command: "mongod --smallfiles"
  volumes:
    - "data/db:/data/db"
  ports:
    - "27017:27017"
```

**Comment by burabure** [comment]
@FreakTheMighty i'm having the same issue here. did you find a work around?

**Comment by burabure** [comment]
it seems the issue was docker picking up another volume from some cache.

````docker-compose rm --force

solved it for me

**Comment by md5** [comment]
@FreakTheMighty In the boot2docker case, using `data/db` will use the `data/db` directory under `pwd`, which is presumably some directory under `/Users`. In that case, the container will see `1000:50` as the user and group ownership of that directory, which is incompatible with the `mongodb` user that the Mongo service in this container runs as. It will also not be able to modify the ownership with `chown -R mongodb:mongodb` as is attempted in the entrypoint.

If you're willing to abandon having the data directly on your host hard drive in the local `data/db` directory, you should be able to get things working by doing something like "`/mnt/sda/var/lib/mongo-data:/data/db`" for your volume mount. This will use the b2d data disk instead of your local disk.

Beware that if you do this, you will be using the same disk space for Docker images and your Mongo data. If you want to avoid that issue, you'd need to add a separate data disk to your boot2docker VM.

**Comment by FreakTheMighty** [comment]
@md5 thanks for your tips. This clarify what is happening. 

I was able to get mongo data to persist within the VM, but I don't think this is a good long term solution. The issue is that when the VM goes down, the mongo database is lost. While this setup is only for development, I think it will be painful to lose state each time boot2docker goes up or down.

Would adding a separate data disk have the same short coming?

**Comment by md5** [comment]
@FreakTheMighty the data shouldn't go away when b2d goes up and down, since it's stored on your data disk. Only if you actually delete the b2d VM and recreate it would the main data disk go away.

**Comment by FreakTheMighty** [comment]
Hmm, perhaps I'm missing something, but here's the simple test that led me to that conclusion:
```
boot2docker ssh
sudo touch /mnt/sda/var/lib/mongo-data/persist
# exit
boot2docker restart
boot2docker ssh
ls /mnt/sda/var/lib/mongo-data/
```
The `persist` file is gone.

**Comment by md5** [comment]
On my VM, that directory is `/mnt/sda1`, not `/mnt/sda`.

**Comment by FreakTheMighty** [comment]
@md5 thank you very much, it worked! Just to be clear, how can I tell which mounts are persistent?

**Comment by md5** [comment]
In 99% of b2d cases, there will only be one data disk and it will be mounted at `/mnt/sda1`.
