### ISSUE TITLE
Can't connect to mongo container from my apps container on the same docker machine, but I can connect to the mongo container from outside

### ISSUE THREAD

**Issue by RyanSusana** [docker-library/mongo#267]
Hello contributors,

My problem is that I am running mongo on a vps via docker like so:
`docker run -p 27017:27017 --name flowers-db -v /ise/datadir:/data/flower -d mongo --auth`

I setup user roles etc...
Everything runs perfectly

I then curl from the vps and from my own local machine to the docker ip:port and everything is smooth

I then test my app using the ip for mongo and port, everything runs smooth

I then dockerize my app and run it alongside the mongo container and I get a timeout exception(Java Driver btw)

I think to myself that maybe I set it up wrong so I run the same dockerized app to connect to the same db from another docker-machine and it runs perfectly again.

I had a similar setup a couple months ago and it ran nicely. But only now I get these issues. Am I missing something?

**Comment by wglambert** [comment]
When you use the `-p` flag to expose ports, they are only exposed to the host machine, not to other containers.

To get containers to see each other they either need to be on the same Docker network or linked through the legacy `--link <Container name or hostname>`

It seems the containers aren't on the same network or linked, so try making a user-defined bridge network `docker network create -d bridge new_bridge`

Then `run` the containers with `--network new_bridge`

When using a user-defined network the containers can also identify each other through hostnames instead of just IP addresses:
https://docs.docker.com/network/bridge/
https://docs.docker.com/network/links/
