### ISSUE TITLE
No matching manifest for unknown in the manifest list entries.

### ISSUE THREAD

**Issue by abhinav2127** [docker-library/mongo#309]
Unable to pull MongoDB docker container to set up my project environment.
My system configuration is Raspbian - Linux Raspberry PI 3v Model B
Installed docker and tested with Hello-World docker image.

When trying with "docker pull mongo" I am getting this error message

Using default tag: latest
latest: Pulling from library/mongo
no matching manifest for unknown in the manifest list entries.

Please help with this issue if it is running for Debian Linux.

**Comment by wglambert** [comment]
Did you try `docker pull arm64v8/mongo` to pull the specific one for your architecture

**Comment by yosifkit** [comment]
While the Raspberry Pi 3 is an arm64 board, using Raspbian means that kernel and all the binaries are "Raspbian `armhf`" (ie arm32v6 in docker images). The MongoDB images only support `arm64v8`, `amd64`, and `windows-amd64`.

**Comment by yosifkit** [comment]
@txgruppi

I would guess that your board is not running with an arm64v8 kernel (and is probably `arm32v6` as I noted above is common on RPi3) since `*/mongo:4` is a [`Shared Tag`](https://github.com/docker-library/mongo/issues/316).

The `mongo:4` tag is a manifest list and looks fine to me, but `redis` and `eclipse-mosquitto` are not manifest lists (just a single image), so they can be pulled regardless of host platform.

```console
$ manifest-tool inspect arm64v8/mongo:4
Name:   arm64v8/mongo:4 (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:ae8e90a3ace48539fe2d77506ae17f2dedb6e189752102ddb070e8f7587b3850
 * Contains 1 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:1af4c7099a6fe48d95b6cf7601a35d34400570d8fd185b76aa45faed91b29480
1  Mfst Length: 3029
1     Platform:
1           -      OS: linux
1           - OS Vers: 
1           - OS Feat: []
1           -    Arch: arm64
1           - Variant: v8
1           - Feature: 
1     # Layers: 13
...

VS

$ manifest-tool inspect arm64v8/redis:5-alpine
arm64v8/redis:5-alpine: manifest type: application/vnd.docker.distribution.manifest.v2+json
      Digest: sha256:00a7e3b52fffb2faec1323002e4a364e04152573f9ec8d7dc51b8d79a2318224
Architecture: arm64
          OS: linux
    # Layers: 7

```

You should be able to work around it by pulling a more specific tag like `arm64v8/mongo:4-xenial`, but I can't guarantee it will run.

**Comment by txgruppi** [comment]
@yosifkit thanks for help, it worked for `arm64v8/mongo:4-xenail`.

Could the problem be because of `arm64` vs `aarch64`?

```Linux pine64 3.10.105-bsp-1.2-ayufan-136 #1 SMP PREEMPT Sat Oct 27 21:18:35 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux```
