### ISSUE TITLE
 Remove MongoDB - License issue

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/mongo#324]
As [RedHat and Debian removed MongoDB](https://www.zdnet.com/article/mongodb-open-source-server-side-public-license-rejected/) from their catalog, I think we'll have to do the same here.

Does anybody has access to a lawyer to answer these questions?

**Comment by tianon** [comment]
So at least in the case of Debian, it was removed because it's now explicitly non-free according to the DFSG (https://www.debian.org/social_contract#guidelines -- all software in Debian's "main" must comply with these guidelines).  I'm guessing RedHat was probably for similar reasons.

In the case of this repository, we're really providing the binary bits that MongoDB Inc themselves officially publish, simply pre-packaged and ready for immediate use.  It's typically been our approach that complying with binary distribution and use licenses is definitely the purview of our users (see, for example, the common boilerplate we add to every image description: https://github.com/docker-library/docs/blob/51aabaab0c571d39e2f22326b940fc234b97b42d/.template-helpers/license-common.md).

I definitely think we should update https://github.com/docker-library/docs/blob/master/mongo/license.md to point out explicitly that the license is SSPL and that users of the software should take extra care to comply (which is generally sound advice, but I am definitely not a lawyer).

I think the hardest part about getting a real official legal comment on this is getting a lawyer who not only understands the nuances of open source licenses (which is the easy half) but also understands the nuances of the packaging that Debian and RedHat do versus what is provided by this repository.

(As a side note, IMO this is also a pretty additional strong case against providing Alpine variants unless/until MongoDB Inc provides official binary releases supporting it.)

I'd also love to get some input on this sort of thing from MongoDB Inc directly, but attempts to engage them previously haven't been very fruitful. :disappointed:

**Comment by pierreozoux** [comment]
Is docker official images shipping other proprietary software?
As it is being removed from debian, it might be from ubuntu.
But then the question will be will you refactor the repo to still provide this docker image?

I'm just curious. At the end, it is Docker inc responsability to ship proprietary code or not. Feel free to close this issue if you don't find it relevant.

**Comment by tianon** [comment]
There are other official images which ship proprietary code, yes (we only
officially require that the image source code itself in the form of a
Dockerfile + context be available in some form we can consume to build --
otherwise we wouldn't be able to build/push an image).
