### ISSUE TITLE
Update base image to bionic

### ISSUE THREAD

**Issue by agowa338** [docker-library/mongo#326]
Please update the base image for e.g. latest and unstable from xenial to bionic.

The go version in xenial is old and lacks support for running with qemu.
Therefore the container is not able to start on platforms other than x64 and arm8.

The related issue was resolved over two years ago, but xenial has not received that update...
https://github.com/golang/go/issues/20763

**Comment by yosifkit** [comment]
I'm a bit confused. This is the image for MongoDB, not the Go language. So what does the go version in Xenial have to do with this? Go binaries should be built in their own image and run in their own container.

Also, we use Xenial since it is the one with the most supported architectures from [MongoDB](https://docs.mongodb.com/manual/installation/#mongodb-supported-platforms), and that is limited to only amd64, and arm64v8.
