### ISSUE TITLE
Get:35 http://repo.mongodb.org/apt/debian/ jessie/mongodb-org/3.4/main mongodb-org-shell amd64 3.4.19 [8070 kB]

### ISSUE THREAD

**Issue by dongwenda** [docker-library/mongo#332]
![image](https://user-images.githubusercontent.com/40119890/52405979-91a84400-2b07-11e9-88ae-3c2897b2987c.png)

How can I do

**Comment by wglambert** [comment]
Since there isn't anything denoting an error with the image I'm going to close.

If you have further questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
