### ISSUE TITLE
account home directory creation in docker_entrypoint.sh

### ISSUE THREAD

**Issue by burkett123** [docker-library/mongo#360]
Get this error message when using docker_entrypoint_initdb.d to add root user to mongodb at instance startup (from docker logs <container>:  
2019-07-23T21:34:32.039+0000 E -        [main] Error saving history file: FileOpenFailed: Unable to open() file /home/mongodb/.dbshell: Unknown error
  I believe the /home/mongodb directory is not created by docker_entrypoint.sh (running as root?).
Just starting to explore docker and all of the related technologies. Please forgive if I raise a point that has been long settled.
Thanks.

**Comment by wglambert** [comment]
Looks like https://github.com/docker-library/mongo/issues/323

Does using the [environment variables](https://github.com/docker-library/docs/tree/master/mongo#environment-variables) work for you?

Otherwise making that directory/file should work

**Comment by wglambert** [comment]
Closing since this doesn't seem to be an issue with the image 
If you have further questions you could also try asking the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
