### ISSUE TITLE
how can I use --httpinterface to open 28017 with docker-compose.yml

### ISSUE THREAD

**Issue by 786744873** [docker-library/mongo#363]
I want use 28017 port to manage mongodb.

docker-compose.yml

> version: '3.7'

services:

  mongo:
    image: mongo:4.0.10
    container_name: mongo_node1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo_2o19
      TZ: Asia/Shanghai
    volumes: 
      - mongo_data_configdb:/data/configdb
      - mongo_data_db:/data/db
    ports: 
      - 1060:27017
      - 1062:28017

volumes: 
  mongo_data_configdb: 
    driver: local
  mongo_data_db: 
    driver: local

**Comment by wglambert** [comment]
Give it a [command](https://docs.docker.com/compose/compose-file/#command) with `--port=28017` to Mongo
https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-port

Going into the container's network namespace to see what port is open:
```console
$ docker run -d --rm --name mongo -p 28017:28017 mongo --port=28017
5ea112df2f30960b27f681a4b1789f6ec577a4753376fe156ce5cc79541ca7e9

$ docker run -it --rm --network=container:mongo --pid=container:mongo tianon/network-toolbox bash

root@5ea112df2f30:/# netstat -tulpn
Active Internet connections (only servers)                                                                                                        
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name                                                  
tcp        0      0 0.0.0.0:28017           0.0.0.0:*               LISTEN      -
```

If you have further questions you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

**Comment by cool21540125** [comment]
I think the OP wants to access mongodb web interface, not just change its port from 27017 to 28017

**Comment by yosifkit** [comment]
The `httpinterface` was removed in MongoDB 3.6: https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#http-interface-and-rest-api
