### ISSUE TITLE
Windows Server 2019 support

### ISSUE THREAD

**Issue by awakecoding** [docker-library/mongo#375]
I am building a container-based application for Windows Server 2019, and all of my applications have containers compatible with Windows Server 2019 except MongoDB. Because Windows container compatibility is restrictive, the current image based on Windows Server 2016 won't work with 2019.

Would it be possible to provide images based on "mcr.microsoft.com/windows/servercore:ltsc2019" ?

We have made our own container following recommendations from this blog post: https://ulyaoth.com/tutorials/how-to-install-mongodb-4-0-in-replication-on-windows-server-2019/

It is basically just the same Dockerfile as for 2016, except for 2019, and using the MongoDB .msi installer for 2008 R2.

**Comment by tianon** [comment]
If you look at the detail listing for https://hub.docker.com/_/microsoft-windows-servercore, I'll note that `1809` and `ltsc2019` are currently at the exact same "OS Version" ("10.0.17763.864") because `1809` *is* `ltcs2019` (which is why we don't have an explicit `ltsc2019` tag -- `1809` is currently the same thing, but much more specific as one has to be for Windows support to actually work).

**Comment by awakecoding** [comment]
@tianon did you mean 1803 (10.0.17134.1130)? 1809 (10.0.17763.864) does exist, but there is no mongo docker image for 1809, only 1803. I have tried 1803 on Windows Server 2019, and it throws the "The container operating system does not match the host operating system" error.

**Comment by tianon** [comment]
Doh!  I thought we had 1809 here, sorry!  That should be added in https://github.com/docker-library/mongo/pull/376 :+1:

**Comment by awakecoding** [comment]
@tianon wow, thanks a lot! We have our own 2019 image in the meantime, but I will definitely switch to the official one when it becomes available :)
