### ISSUE TITLE
Update mongo 3.2 tag

### ISSUE THREAD

**Issue by tbruun** [docker-library/mongo#377]
I know 3.2 is EOL, but the last version on the 3.2 tag is 3.2.21.
This version contains a bug for initial sync fixed in 3.2.22: [SERVER-38425](https://jira.mongodb.org/browse/SERVER-38425)

Can 3.2 tag be updated to the last version ?

Current version:
```
docker run -it mongo:3.2
2019-12-07T11:57:56.345+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=73767fdf60bd
2019-12-07T11:57:56.345+0000 I CONTROL  [initandlisten] db version v3.2.21
```

**Comment by yosifkit** [comment]
That was nice of them to [make a release with the fix](https://docs.mongodb.com/manual/release-notes/3.2/#dec-28-2018) 4 days after we [removed it](https://github.com/docker-library/mongo/commit/c5720ca1880815d78c3f1b58a8a30003b1724efd) from this repo (and 2 months after end of support).  At this point it is almost a full 12 months since it was removed (and 14 months out of support), so I don't really want to add it back for a single version bump.  I'd recommend just building your own image by going to the commit just before removal and running `./update.sh` and it should just work to update the `3.2/Dockerfile`.
