### ISSUE TITLE
Manifest for s390x broken

### ISSUE THREAD

**Issue by tdaleibm** [docker-library/mongo#384]
`docker pull mongo` on s390x now fails with "Failed to pull image "mongo:4.0": rpc error: code = Unknown desc = no image found in manifest list for architecture s390x, OS linux" . To fix this issue I had to pull from s390x/mongo. Did something happen to the s390x manifest listing? I see on the https://hub.docker.com/r/s390x/mongo a warning saying WARNING: THIS IMAGE IS NOT SUPPORTED ON THE s390x ARCHITECTURE. Thanks

**Comment by tianon** [comment]
Yeah, this is not necessarily unexpected (although is certainly unpleasant) -- with the release of 4.2.3, MongoDB appears to have started publishing `arm64v8` packages again, while at the same time they've stopped publishing for `s390x`: https://github.com/docker-library/mongo/commit/b9f46d094dcfb0cd7bd970de20505b6e69f90932. :disappointed:
(See https://github.com/docker-library/mongo/issues/378 for a similar issue when 4.2.2 removed arm64 support.)

As a workaround, you should be able to use `mongo:4.2.2` or `s390x/mongo:4.2`.

All that being said, it *is* still listed on https://docs.mongodb.com/manual/installation/#s390x as being supported, so hopefully this is just an oversight and thus something could/will be done about it?  (You'd unfortunately have to take that question upstream to clarify that, however.)

**Comment by james-crowley** [comment]
@tianon Thanks for getting back so quick! 

Pulling from `s390x/mongo:4.2.X` works.

From the commit you mentioned, https://github.com/docker-library/mongo/commit/b9f46d094dcfb0cd7bd970de20505b6e69f90932, it seems to be made by the `docker-library-bot`, that commits is getting trigger somewhere right?

You mentioned to take it upstream, but I am not sure where to go since the mongo images seem to be built from https://github.com/docker-library/mongo. The maintainers being you and @yosifkit. 

I see that the https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/multiverse/binary-s390x/, is missing a release of 4.2.3, hence why `s390x` was removed. I'll raise an issue over at https://github.com/mongodb/mongo and see if I can get some more information.

**Comment by james-crowley** [comment]
https://jira.mongodb.org/browse/SERVER-45879

**Comment by james-crowley** [comment]
@tianon https://github.com/docker-library/mongo/commit/7eb154bcb0b90a70effe73dd8ab77783ce85434a Thank you!

@tdaleibm FYI, should be fixed soon!

**Comment by james-crowley** [comment]
@tianon Thanks for pushing the manifest file. Looks like you can close out this issue.
