### ISSUE TITLE
issues when using Windows Server containers with the February 11, 2020 security update release

### ISSUE THREAD

**Issue by mawl** [docker-library/mongo#389]
Hey,

Can you please release new windows images (ltsc206, ltsc2019) for mongo as of this microsoft issue?

https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t

Container mongo:3.4.10-windowsservercore actually crashes on windows server 2016 with:

`Exited (3221226505) 2 hours ago `

Thanks and regards,
Marco

**Comment by yosifkit** [comment]
Version 3.4 is end of life Jan 2020 (https://www.mongodb.com/support-policy).  We rebuild windows based images frequently to get the windows patch releases. Please use a version of MongoDB that is supported (and thus gets rebuilt).

Since your host is newer, you should be able to run them with --isolation=hyperv as a workaround.
