### ISSUE TITLE
db.collection.watch() not available

### ISSUE THREAD

**Issue by bergkvist** [docker-library/mongo#395]
# Change Streams
[db.collection.watch()](https://docs.mongodb.com/manual/reference/method/db.collection.watch/) allows for listening to changes as they happen, rather than polling/diffing the db to find out if something has changed. MongoDB has named this idea "change streams".

This is stated as being "*For replica sets and sharded clusters only*". 

## What I'm about to say is going to sound radical.

**I consider this to be a bug.** Change streams should be available by default. 

I believe the `mongo:latest` (default) image should have the oplog/change streams enabled - as to allow for using db.collection.watch().

**Comment by tianon** [comment]
I appreciate that you'd like this to be available by default, but this isn't something we can affect in the Docker image -- this is an intentional choice for this feature by MongoDB upstream, so I'd recommend you take this feature request there so that they can consider implementing it for a future release.

Closing, since there's really nothing we can do here (this is just the Docker image packaging for MongoDB, and we can't really affect what features/functionality are available from the upstream packages we consume).
