### ISSUE TITLE
AuthenticationFailed: SCRAM authentication failed, storedKey mismatch

### ISSUE THREAD

**Issue by ruanpablom** [docker-library/mongo#408]
When I try to login in admin database using Mongo compass this error is returned: ```ACCESS   [conn6] SASL SCRAM-SHA-256 authentication failed for root on admin from client 192.168.0.10:44938 ; AuthenticationFailed: SCRAM authentication failed, storedKey mismatch```

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by wglambert** [comment]
Going to close assuming you resolved the issue

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by lvergergsk** [comment]
same error occur
