### ISSUE TITLE
Extend mongo image with ssh

### ISSUE THREAD

**Issue by mcherb** [docker-library/mongo#413]
I want to extend the mongo image with a ssh server

I’ve written this lines : 

```
FROM mongo

RUN apt-get update && \
    apt-get install -y openssh-server

EXPOSE 22

RUN useradd -s /bin/bash -p $(openssl passwd -1 test) -d /home/nf2/ -m -G sudo test

CMD ["sh", "-c", "service ssh start", "bash"]
```

But this will run either ssh or mongo not both at the same time !

Any idea on how to to it ?

Thanks in advance

**Comment by tianon** [comment]
You're going to need some kind of process supervisor to run both processes.  Instead of running SSH inside your container, I'd suggest using SSH on the host, and using `docker exec` to get a shell inside the container.

In the future (and for further assistance), these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
