### ISSUE TITLE
Dockerfile build cannot find systemctl to finish mongo-org-server --configure setup in postinst

### ISSUE THREAD

**Issue by Haythamamin** [docker-library/mongo#419]
I am trying to build a mongo image based on 4.4 dockerfile. I see a step was added to remove systemctl `# && rm -f /usr/local/bin/systemctl \` but I cant find it to even finish the postinst script steps. I tried adding systemd maually, but ran into `system has not been booted with systemd as init system (pid 1). can't operate.` Any advice? 
Dockerfile for Mongo 4.4 Ubuntu:bionic image

**Comment by wglambert** [comment]
You could do something like `ln -s /bin/echo /bin/systemctl` which fixed this issue for Dockerized OmniDB https://github.com/OmniDB/OmniDB/issues/838 https://github.com/OmniDB/OmniDB/pull/872
>fix broken install due to missing systemctl with link to echo as systemctl has no meaning inside docker container

I would ask over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
