### ISSUE TITLE
Connection refused from docker to docker on port 27022

### ISSUE THREAD

**Issue by vitalybrandes** [docker-library/mongo#420]
Running mongo container on latest windows 10 update.
Docker (WSL 2) with ubuntu.
I have asp dot net core api CRUD applications that connect to mongo db and running as Docker.
Once i am running container  with 27017 port, everething is ok
`docker run --name mongo -d -p **27017**:27017 mongo --bind_ip_all`
but if i change to any other port 27019, 27022 etc
`docker run --name mongo -d -p **27019**:27017 mongo --bind_ip_all`
i get `Connection refused 172.17.0.3:27022`

Why? :-(

**Comment by wglambert** [comment]
If you're directly connecting to the container then the port forwarded using the `-p` option won't affect that connection, it only forwards that port through the host's firewall to allow for external connectivity to the container. Example https://github.com/docker-library/postgres/issues/650#issuecomment-562253607

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by vitalybrandes** [comment]
Thank you!
