### ISSUE TITLE
Port appears to be hardcoded

### ISSUE THREAD

**Issue by ng5** [docker-library/mongo#422]
Is it possible to add a new variable MONGO_PORT to accept this from user. At the moment it seems to always use 27017,  which is fine if image is being executed in isolated docker network.

I tried to pass --port argument to CMD but it didn't work.

I need to setup 2 instances on host network and both containers attempt to start on 27017 causing port already in use error.

**Comment by wglambert** [comment]
I can't reproduce any issues with using `--port` https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-port
```console
$ docker run -d --rm --name mongo mongo --port=28018
51447d094815c6c94e817a8621d19dab83aa1fe7fbfda0ec82361a4afdaf3f5d

$ docker run -it --rm --network=container:mongo --pid=container:mongo tianon/network-toolbox netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:28018           0.0.0.0:*               LISTEN      -
```

**Comment by r0hitv** [comment]
As you can see below, I need port on local network, even after you passed --port argument it is still bound to 27017 on local machine.

```
➜  ~ docker run -d --rm --name mongo mongo --port=28018
ba4aa2f19788269839292c8872079c46de435534e7d0cb09ea68b13058baaafa
➜  ~ docker ps | grep -i mongo                         
ba4aa2f19788        mongo                "docker-entrypoint.s…"   8 seconds ago       Up 7 seconds        27017/tcp                                        mongo
➜  ~ docker ps | grep -i mongo
ba4aa2f19788        mongo                "docker-entrypoint.s…"   13 seconds ago      Up 12 seconds       27017/tcp                                        mongo
➜  ~ mongo --port 28018       
MongoDB shell version v4.4.0
connecting to: mongodb://127.0.0.1:28018/?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 127.0.0.1:28018, connection attempt failed: SocketException: Error connecting to 127.0.0.1:28018 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:362:17
@(connect):2:6
exception: connect failed
exiting with code 1
➜  ~ 

```

**Comment by r0hitv** [comment]
It will only work when **--network=host** is specified, however I will lose flexibility to initialise the database which is available through /docker-entrypoint-initdb.d/ system when you use docker-compose instead of command line. 

➜  ~ docker run -d --rm **--network=host** --name mongo mongo --port=28018
3eb67fed36d44d710efa9f564760932f7cb9860921d0be82549b92da508aca6d

**Comment by wglambert** [comment]
Ah, you're wanting https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose

When you said `on host network` I thought you meant `--network=host` https://docs.docker.com/network/host/
So actually you don't need to give mongo any `--port` commands as Docker's `-p` will forward whatever port on the host -> container. Then your containers can use the same `27017` port internally 

Also in your `docker ps` the port you're seeing is due to the `expose 27017` in the Dockerfile, it's more of a notice to the users of ports they should be aware of. If you go into the container and do a `netstat -tulpn` you'd see it's listening on the `--port` you gave to mongo like in my example above
https://github.com/docker-library/mongo/blob/f79f35ce16c972632c38f74d1e70b4cdb419f2ed/4.4/Dockerfile#L110

So here I'm forwarding `27018` on the host -> container. And internally to the container nothing's changed, it's still listening on 27017 but any traffic hitting the host on its forwarded port `27018` will be directed to that container.
```console
$ docker run -d --rm --name mongo -p 28018:28017 mongo
99361485fbf87aa7a1d3922a195a350b01f6409310813a2f027fd2a5b442e4e1

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                 NAMES
99361485fbf8        mongo               "docker-entrypoint.s…"   6 seconds ago       Up 4 seconds        27017/tcp, 0.0.0.0:28018->28017/tcp   mongo

$ docker run -it --rm --network=container:mongo --pid=container:mongo tianon/network-toolbox netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      -
```

For more information I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by r0hitv** [comment]
wglambert - thanks for looking into. I'm aware of the port forwarding in docker, but there are several issues i have noticed with this image, therefore i decided to write my own scripts using systemd without docker.  issues are following:

All of these problems can be solved by introducing a new variables MONGO_PORT, so that instead of 
**EXPOSE 27017** - it can expose port needed by the users. Feel free to close this issue if this is not relevant for this repo.

1) If you use docker's internal network, then replica set can't find any other hostname outside this network. 
2) You will be forced to use docker swarm or some other orchestration frameworks like k8s or you need to pass complex DNS server and setup firewall rules manually to your containers.

My requirements are very simple: I want to create and initialize mongo using this docker image but want to keep all the good features provided by /docker-entrypoint-initdb.d/. My only requirement is to use --network=host.  As far as I know and i've tried this in the past: Port mapping does not with replica set.

192.168.0.101 host1: container starts using port mapping 27017:27017 (PRIMARY) ip: 
192.168.0.102 host2: container starts using port mapping 27017:27017 (SECONDARY)

At this point, if you initiate replica set on host1 by adding host2:27017, it will fail because container is not aware of host2. You really do need to use --network=host or setup up complex dns/firewall rules.

**Comment by tianon** [comment]
> All of these problems can be solved by introducing a new variables MONGO_PORT, so that instead of
> **EXPOSE 27017** - it can expose port needed by the users. Feel free to close this issue if this is not relevant for this repo.

Unfortunately, `EXPOSE` can take a variable, but it's expanded at build time, not at runtime, so it won't have any effect.  Besides that though, the `EXPOSE` value is merely a suggestion/metadata, and doesn't have any effect unless you use Docker's `--publish-all` flag.

> 1. If you use docker's internal network, then replica set can't find any other hostname outside this network.

That's true, but making a Docker network "internal" is an optional flag, so I'm confused why that's an issue?  I'm not sure why your MongoDB instance needs to reach the internet, but it's easy enough to use a non-internal network.

> 2. You will be forced to use docker swarm or some other orchestration frameworks like k8s or you need to pass complex DNS server and setup firewall rules manually to your containers.

I'm not sure why you want to run MongoDB in a container, but not your other services (the opposite is much more common), but this shouldn't be too hard.

> My requirements are very simple: I want to create and initialize mongo using this docker image but want to keep all the good features provided by /docker-entrypoint-initdb.d/. My only requirement is to use --network=host. As far as I know and i've tried this in the past: Port mapping does not with replica set.
> 
> 192.168.0.101 host1: container starts using port mapping 27017:27017 (PRIMARY) ip:
> 192.168.0.102 host2: container starts using port mapping 27017:27017 (SECONDARY)
> 
> At this point, if you initiate replica set on host1 by adding host2:27017, it will fail because container is not aware of host2. You really do need to use --network=host or setup up complex dns/firewall rules.

You can combine Docker's networks with port exposing, so you could do `--network db` with `-p 27017` (and use `--name host1` and `--name host2` or `--network-alias` if you want the containers to able to reference each other by name the same as external hosts do).  I'm not sure why you'd need complex firewall rules, but if your host DNS resolves `host1` and `host2` appropriately, then you shouldn't even need to do that, and just `-p 27017` should be sufficient (but you'll have to make sure they know their hostname, so I'd suggest doing `--hostname host1` and `--hostname host2`).

All that being said, in the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker), as these aren't really things we can fix in the image, but more questions of general Docker / MongoDB usage.
