### ISSUE TITLE
Docker-compose automate creating replicaset for build pipelines

### ISSUE THREAD

**Issue by farzadz** [docker-library/mongo#425]
I recently tried creating a standalone replica set for a build pipeline that uses multi-document transactions in tests. The issue is that the host is only available when the build is running and I cannot manually run `rs.initiate()` for cluster setup.  From the docs and [this](https://github.com/docker-library/mongo/issues/359) issue I came up with this (there are more services in the compose file but I skipped them here):

``` compose.yml
version: '3'

services:

  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - /etc/mongod.conf:/etc/mongod.conf
      - /etc/mongo-setup:/docker-entrypoint-initdb.d
    entrypoint: [ "mongod","-f","/etc/mongod.conf" ]
    restart: always
```
The contents of `/etc/mongod.conf` is as follows:

``` conf.yaml
storage:
  dbPath: /data/db
  journal:
    enabled: true

net:
  port: 27017
  bindIp: 0.0.0.0


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

#operationProfiling:

replication:
  replSetName: rp0
  ```

and `/etc/mongo-setup` contains a simple `.sh` file with this single line:
```mongo.sh
mongo --eval "rs.initiate()"
```
Later, I noticed because I changed the entrypoint in the compose file, `docker-entrypoint.sh` is not run and as a result, the shell file in `docker-entrypoint-initdb.d` is skipped. Any help regarding this is much appreciated.

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/mongo#using-a-custom-mongodb-configuration-file
You should pass `--config /etc/mongod.conf` as a command rather than overwriting the entrypoint. The entrypoint will forward the command when it finishes


For further help you should try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
There was also this thread that has a lot of discussion around replica sets https://github.com/docker-library/mongo/issues/246
