### ISSUE TITLE
mongodb configuration file.

### ISSUE THREAD

**Issue by nabadas** [docker-library/mongo#427]
Hi,
Please can you told mongodb.conf file not found, mongodb.conf.origin file found. please help me. it's urgently.

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

If you wanted to use a custom file it would look like this https://github.com/docker-library/docs/tree/master/mongo#using-a-custom-mongodb-configuration-file

**Comment by tianon** [comment]
The image doesn't come with a configuration file because without one, MongoDB already has pretty sensible defaults and providing/using a configuration file is optional (you're welcome to provide your own via bind mount, creating a new image that's `FROM` this one, Docker Config/Secret objects, etc).
