### ISSUE TITLE
Unable to initialize mongo on a custom path using --dbpath

### ISSUE THREAD

**Issue by jerrydevin96** [docker-library/mongo#428]
While trying to initialize mongo with a custom path, I am getting error in logs as path configured is read only and the container stops.
![image](https://user-images.githubusercontent.com/51227952/96962463-77eda100-1524-11eb-8bd8-30780b9a5845.png)

**Comment by wglambert** [comment]
`attempted to create a lock file on a read-only directory: /data/test/db`
What are the permissions on that directory?

Can you give all the commands you ran and any relevant files

**Comment by jerrydevin96** [comment]
I tried initialising mongo container using the below command:
docker run -d -p 110:27017 mongo --dbpath /data/test/db --replSet test

I was trying to initialise the DB on a custom path and I assumed that the folder structure will be created during container creation.

**Comment by tianon** [comment]
I tried your example, and rather than errors about a "read-only directory", I simply get an error that the path does not exist:

`{"t":{"$date":"2020-10-26T19:16:42.300+00:00"},"s":"E",  "c":"STORAGE",  "id":20557,   "ctx":"initandlisten","msg":"DBException in initAndListen, terminating","attr":{"error":"NonExistentPath: Data directory /data/test/db not found. Create the missing directory or specify another path using (1) the --dbpath command line option, or (2) by adding the 'storage.dbPath' option in the configuration file."}}`

If I also include a new volume at `/data/test/db`, then I get the failure you've described, presumably because Docker creates that directory with `root:root` permissions, which the MongoDB user then cannot access.

Is there a particular reason for using this path instead of the `/data/db` default?

**Comment by jerrydevin96** [comment]
@tianon I was checking this out for a special kubernates use case. I am trying to deploy mongo db as a replica set on an AWS EKS cluster with AWS EFS as the persistent volume. As EFS does not allow dynamic provisioning of volumes, we had to find a work around with varying Mount paths in the same volume. But I am not able to specify a custom db path and am getting the errors you have mentioned. I solved this issue by creating a custom entry point script.

**Comment by wglambert** [comment]
Since you've got it resolved with a workaround for your usecase I'm going to close then 👍 
I'm curious though why you chose EFS over EBS, considering the functionality you get with EBS using a [CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) for [volume snapshots](https://kubernetes.io/docs/concepts/storage/volume-snapshots/) and dynamic provisioning

**Comment by jerrydevin96** [comment]
@wglambert we are looking to replicate our application across 2 different regions. One region acting as the primary and the other for disaster recovery. EFS seemed like a better option because it allows for syncing data between multiple regions (through AWS data sync I believe). Thanks for providing info about volume snapshots I have not explored it yet.
