### ISSUE TITLE
How to enable environment variables (INITDB USERNAME, INITDB PASSWORD ) with Pre-existing database

### ISSUE THREAD

**Issue by imageschool** [docker-library/mongo#517]
Hi, by looking at this (https://github.com/docker-library/docs/tree/master/mongo#environment-variables) I understood the environment variables (**MONGO_INITDB_ROOT_USERNAME, MONGO_INITDB_ROOT_PASSWORD**) does not take any effect if i launch mongo container with pre-existing database (/data/db volume mounts)

I have few questions regarding this,

1. If possible, how can I enable those environment variables so I can launch my mongo container with auth enabled and also using **pre-existing database** ?

2. Although the environment variables are ignored when running with pre-existing database contained volume, if i set them, they still enables authentication (if i am right, it uses mongod --auth flag which enables authentication)

So, when running a authentication enabled mongo container with pre-existing database(/data/db volume mount), 
what are my username & password?

**Comment by wglambert** [comment]
Those environment variables are tailored for when it's doing the database initialization, so there isn't a version of them that affects a populated database
https://github.com/docker-library/mongo/blob/master/5.0/docker-entrypoint.sh

If you're running a populated database then the authentication credentials are what it was initialized with.

Another option you could do is create a `.sh` or `.js` script to automatically populate the database that the container creates https://github.com/docker-library/docs/tree/master/mongo#initializing-a-fresh-instance
This would allow for your data to be exported to the container and also have the environment variables take effect

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by imageschool** [comment]
@wglambert Thank you for your insight!
