### ISSUE TITLE
find: 'mongodb' is not the name of a known user

### ISSUE THREAD

**Issue by chengjiansheng** [docker-library/mongo#518]
`docker run  \
>     --name my-mongo \
>     -v /etc:/etc \
>     -v /data/mongo/db:/var/lib/mongo \
>     -v /data/mongo/log:/var/log/mongodb \
>     -p 27018:27017 \
>     -d mongo --config /etc/mongod.conf`

find: 'mongodb' is not the name of a known user

![2022-01-12_112500](https://user-images.githubusercontent.com/11955116/149058678-d19dc179-5818-4529-8b95-6ff30698d47f.png)

**Comment by wglambert** [comment]
Mounting your `/etc/` overwrites the `passwd` file there that has user-uid info. It's not a breaking error in this case just a warning

In the future questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
