### ISSUE TITLE
"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongod.log"

### ISSUE THREAD

**Issue by chengjiansheng** [docker-library/mongo#519]
`docker run \
    --name my-mongo \
    -v /usr/local/etc/mongo:/etc/mongo \
    -v /data/mongo/db:/var/lib/mongo \
    -v /data/mongo/log:/var/log/mongodb \
    -p 27017:27017 \
    -d mongo --config /etc/mongo/mongod.conf`

![image](https://user-images.githubusercontent.com/11955116/149059057-463849fb-981a-4cae-ba53-9f9223be4140.png)

`systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

storage:
  dbPath: /var/lib/mongo
  journal:
    enabled: true

processManagement:
  fork: false  
  pidFilePath: /var/run/mongodb/mongod.pid 
  timeZoneInfo: /usr/share/zoneinfo

net:
  port: 27017
  bindIp: 0.0.0.0 

security:
  authorization: enabled`

**Comment by wglambert** [comment]
You're mounting the directory that has that file `/var/log/mongodb/mongod.log`. So it seems like it could be an issue with permissions

I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
