### ISSUE TITLE
It looks like you are trying to access MongoDB over HTTP on the native driver port.

### ISSUE THREAD

**Issue by Anik422** [docker-library/mongo#577]
It looks like you are trying to access MongoDB over HTTP on the native driver port.

**Comment by wglambert** [comment]
You're using [`mongoexpress`](https://hub.docker.com/_/mongo-express)? Would need more information to understand the issue. If you're using the example `docker-compose.yml` file try connecting to port 8081 https://github.com/docker-library/docs/tree/master/mongo#-via-docker-stack-deploy-or-docker-compose

In the future questions like these are better asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
