### ISSUE TITLE
Update Pushed to 4.4.23 Tag Breaks Backward Compatibility Without a Version Bump (INI-Style Config)

### ISSUE THREAD

**Issue by mohammad-matini** [docker-library/mongo#590]
We are running a production cluster of MongoDB 4.2 on Docker Swarm, using the old INI-style of config files. Our configs were working normally until a few hours ago, then nodes in our cluster started failing because an update to `4.2.23` was pushed around 15 hours ago, which removed support for the INI-style config files from the `docker-entrypoint.sh`.

MongoDB deprecated the INI-style config files, but still supports them for backward compatibility. This [pull-request](https://github.com/docker-library/mongo/pull/588) breaks backward-compatibility, and doesn't even increment the patch version; even deployments pinned to `4.2.23` would break. This [had happened before](https://github.com/docker-library/mongo/issues/445) too, but at least the patch version was incremented at the time.

Shouldn't the decision of completely dropping the old INI-style config support be something decided upstream at the MongoDB level? Shouldn't warnings be published that in the next major version the support will be completely dropped? Having this happen in a sudden update without a warning is disastrous. Admins may only switch new deployments, and testing deployments, to the new YAML-style config, but be conservative with switching their production environments (if it works, don't fix it). Even the accepted Stack-Overflow answer linked in the comments to that removed piece of code says:

> Personally I'm still using the old format and will continue to do so until I see a compelling reason to switch.

Deprecation is _not_ dropping support, it is a signal for people to prepare for a future dropping of functionality, but that drop of functionality _must_ have a published date in advanced, and should ideally come with a major version. Clusters going down suddenly like this is unacceptable, we're even debating whether we should stop using the official images directly because we're losing trust with this QA process. Heck, the pull request description boldly says:

> Also drop a few other bits that are have been longer necessary [...] and ini-style config for MongoDB has been deprecated for a long time.

_Deprecated stuff _must_ not be removed by updating an existing patch version!_

I'm sorry if I come across a bit preachy or aggressive, but I'm frustrated because we're here at 8:30 PM responding to an emergency call for a service deterioration situation caused by this change, and it could have been _much worse_ if we didn't notice it early enough to halt any redeployments.

Please restore functionality removed in this pull-request, and maybe schedule the removal to the next major update _if_ you must remove support at the Docker image level (I'd rather this stay supported until MongoDB drops it, but maybe this is too much of a maintenance burden on you).

For us to simply switch to the new style on production on such short notice is not really feasible. The best we can do on our side is to downgrade to 4.4.22 because it is already tested on our side and still works.

Sorry, again, and thank you for your efforts :)

**Comment by tianon** [comment]
We'll get back to the rest of this, but please please please don't deploy these images directly as-is to production without something doing integration testing to make sure your deploys work successfully first (at the very least, pin them to a content-addressable digest so that you don't get surprised by a tag that changes -- that's why the registry is content-addressable, after all).

**Comment by tianon** [comment]
In #588, we ([mistakenly](https://github.com/mongodb/mongo/blob/0e9ed24634b025de8b7a0f275be7c9303ccc7b1c/src/mongo/util/options_parser/options_parser.cpp#L1887-L1898)) assumed that INI-style configuration files were no longer supported by MongoDB at all, and thus removed the code which detects and then ignores them (which honestly is not likely to work properly with our config parsing over time).  If you want to continue using INI-style configuration files, I would suggest supplying `--entrypoint mongod` to bypass our entrypoint script entirely (in the future).

We plan to bring back the warning for now, but we will probably make it an error at some point in the future (or remove it again), because INI-style config files are not something we support in this packaging of MongoDB.

**Comment by mohammad-matini** [comment]
Thank you :)

> please don't deploy these images directly as-is to production without something doing integration testing to make sure your deploys work successfully first

My client does have integration testing, and staging environments, but they all work based on Docker tags pinned to the patch version (e.g. 4.4.23), and they have already found that version to be working. The production cluster is a dynamic environment with self-healing and stuff, but they all pull from Docker Hub based on the already white-listed image tag. We will think about using digests instead for better reproducibility, and maybe proxying official images in our own docker registry.

> I would suggest supplying --entrypoint mongod to bypass our entrypoint script entirely (in the future).

> We plan to bring back the warning for now, but we will probably make it an error at some point in the future (or remove it again), because INI-style config files are not something we support in this packaging of MongoDB.

I see. We will take that into consideration.

Thanks again for the prompt and helpful response.
I hope you have a great time the rest of your week :)
