### ISSUE TITLE
Docker image documentation adjustment

### ISSUE THREAD

**Issue by Serzhs** [docker-library/mongo#608]
Hello, I had difficulty to understand how to connect Database from [mongoose](https://mongoosejs.com/) while using `stack.yml` example in [mongo docker docs](https://hub.docker.com/_/mongo/).

 I would suggest to add additional information about how to connect database from services like **Mongoose** or **MongoClient** it could look like this:
 
For connecting to database from services like Mongoose you need to open port `27017` within your `stack.yml` file under `mongo` service and in url set option `authSource=admin`

Example:
```
`mongodb://root:example@localhost:27017/<db_name>?authSource=admin`
```

<img width="857" alt="image" src="https://user-images.githubusercontent.com/5610063/221971366-e6cefe02-aeab-4590-80b4-3c499f5991cf.png">

 Thanks for listening!
 
 Best Regards
 Janis

**Comment by tianon** [comment]
We try to avoid actively suggesting that users expose ports, especially to things like databases (and doubly so for databases like MongoDB that default to allowing connection/use without authentication) because users don't often understand the implications of doing so but still blindly copy/paste our examples and then get compromised because they're running on a public instance or something similar (and Docker manages the firewall too, so even users who think they've done what they need to in order to protect themselves are opening the port externally).

What I would suggest is running your containers together in a Docker network and taking advantage of Docker's built-in service discovery with DNS (or using the similar concepts in Kubernetes) for connecting from container to container directly so that your database is not exposed to the host.

See https://docs.docker.com/network/ for more information about Docker's networking model and how to use it effectively for your needs. :bow:

**Comment by godmar** [comment]
> We try to avoid actively suggesting that users expose ports, especially to things like databases (and doubly so for databases like MongoDB that default to allowing connection/use without authentication) because users don't often understand the implications of doing so but still blindly copy/paste our examples and then get compromised because they're running on a public instance or something similar (and Docker manages the firewall too, so even users who think they've done what they need to in order to protect themselves are opening the port externally).
> 

Please consider adding a warning to https://hub.docker.com/_/mongo
