### ISSUE TITLE
MongoDB 5.0+ requires a CPU with AVX support. Container failed to start

### ISSUE THREAD

**Issue by ManojPandey121** [docker-library/mongo#619]
Docker container is not starting and It only shows warning on docker logs

`Docker version : 23.0.4, build f480fb1`
`Docker-compose version: v2.17.2`

docker-compose.yml
```version: '3.8'
services:  
  mongo-db:
    container_name: mongo-db
    image: mongo:6
    volumes:
      - ../psvolumes/mongo6:/data/db
    environment:
      - COMPOSE_PROJECT_NAME=mongo
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 27017:27017
    networks:
      - mongo_network
    restart: unless-stopped
networks:
    mongo_network:
        driver: bridge
``` 

Output:

> [+] Running 2/1
>  ✔ Network ams-api_mongo_network  Created                                                                                                                                        0.1s 
>  ✔ Container mongo-db             Created                                                                                                                                        0.0s 
> Attaching to mongo-db
> mongo-db  | 
> mongo-db  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
> mongo-db  |   see https://jira.mongodb.org/browse/SERVER-54407
> mongo-db  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
> mongo-db  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
> mongo-db  | 
> mongo-db exited with code 0
![image](https://user-images.githubusercontent.com/22314145/235069632-c9ef0ddd-44bf-44ba-8527-8a2a546e7536.png)

This same code is running well on 
`docker: 20.10.23, build 7155243`
`docker-compose: 1.29.2, build 5becea4c`

**Comment by yosifkit** [comment]
The warning is there to let you know why the container is mysteriously crashing (since there is no output from the crashing MongoDB binaries).

I'm a little confused 😕. Are you saying that on one machine that you upgraded docker from `20.10.23` to `23.0.4` and now the `mongo:5` image doesn't run?

If these are separate machines, then it is expected that one might not run it even though it is on a newer version of Docker. The version of Docker is not relevant to this error. The `mongo:5` image requires a CPU that is new enough (one with [AVX support](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX)). The MongoDB 5+ binaries released by MongoDB are compiled with a `-march=sandybridge`, which roughly means "sandybridge or newer", but there are newer CPUs that don't have the required instructions (https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2).

**Comment by ManojPandey121** [comment]
I am trying to run on totally new server. 

> I'm a little confused . Are you saying that on one machine that you upgraded docker from `20.10.23` to `23.0.4` and now the `mongo:5` image doesn't run?

Also tried downgrading the docker to the old version i.e. `20.10.23` and got the same issue. So yes it is not a docker version problem. This same code was running well in another server (container with older mongo images were also running here)  which has almost a similar configuration to the newer one. While trying to setup in totally fresh new server I am having issues. T
 
Since we are running on the container can we solve this by adding some configuration to it?

**Comment by martadinata666** [comment]
If the CPU doesn't have that avx capability, you can pin mongo to an older version like `mongo:4.4.18`

**Comment by yosifkit** [comment]
> Since we are running on the container can we solve this by adding some configuration to it?

Nope, the compiled MongoDB binaries (5.0+) require a CPU with specific instruction support. There is nothing we can do from the Docker side.

**Comment by jmhunter** [comment]
FWIW I worked around this by replacing the binaries in the MongoDB docker image with self-compiled versions with a different '-march' flag.

More details and links to a docker image to help with mongodb compilation on the linked issue here: https://github.com/docker-library/mongo/issues/485#issuecomment-1524109050

**Comment by olaoruku007** [comment]
I pinned Mongodb to older version of mongo:4.4.18 and it worked like magic!  Thank you @martadinata666
