### ISSUE TITLE
The repository 'http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 Release' is not signed.

### ISSUE THREAD

**Issue by maksymkuzko** [docker-library/mongo#711]
I can't build any Docker images from the official Mongo docker hub with Mongo 4.4.any because the GPG key used to verify the MongoDB repository has expired or is no longer valid.

**Comment by yosifkit** [comment]
Mongo 4.4 reached end of life in February 2024 (https://www.mongodb.com/legal/support-policy/lifecycles). The previously built images are still on Docker Hub (so `docker pull mongo:4.4` still works), but as you can see, they are not guaranteed to work (like installing new packages) without hacking around security controls. Since it is end of life, MongoDB would be unlikely to sign them with an updated key.
