### ISSUE TITLE
Possible to use a different filesystem then tmpfs?

### ISSUE THREAD

**Issue by adamgotterer** [docker-library/mongo#94]
I'm mounting a /data/db folder from my host machine that has about 20GB of files. Mongo is unable to start because it says there isn't enough space. It appears that the volume is being mounted into tmpfs instead of using the hard disk. Is there any way around this?

**Comment by tianon** [comment]
Wow, sorry for the uber-long delay here!

If `/data/db` is being mounted via tmpfs, that'd be because you're either using tmpfs for `/var/lib/docker` (unlikely) or an explicit tmpfs mount via `-v`.  By default, this image will simply use a new volume, so should have as much space as your `/var/lib/docker` does.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
